// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.legal-hold@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const LEGAL_HOLD_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const LEGAL_HOLD_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_legal_hold { () => { "{\"capability_id\":\"lenso.legal-hold@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"add_scope\",\"create_hold\",\"get_hold\",\"list_activity\",\"list_holds\",\"release_hold\",\"remove_scope\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_legal_hold_client { () => { "{\"capability_id\":\"lenso.legal-hold@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_legal_hold_client { () => { "{\"capability_id\":\"lenso.legal-hold@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const ADD_SCOPE_OPERATION: &str = "add_scope";
pub const CREATE_HOLD_OPERATION: &str = "create_hold";
pub const GET_HOLD_OPERATION: &str = "get_hold";
pub const LIST_ACTIVITY_OPERATION: &str = "list_activity";
pub const LIST_HOLDS_OPERATION: &str = "list_holds";
pub const RELEASE_HOLD_OPERATION: &str = "release_hold";
pub const REMOVE_SCOPE_OPERATION: &str = "remove_scope";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AddScopeRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub subject: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AddScopeResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "release_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub release_reason: Option<String>,
    #[serde(rename = "released_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_at: Option<Timestamp>,
    #[serde(rename = "released_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes: Vec<HoldScope>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: AddScopeResponseStatus,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HoldScope {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AddScopeResponseStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AddScopeError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateHoldRequest {
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateHoldResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "release_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub release_reason: Option<String>,
    #[serde(rename = "released_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_at: Option<Timestamp>,
    #[serde(rename = "released_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes: Vec<HoldScope>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CreateHoldResponseStatus,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateHoldResponseStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateHoldError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetHoldRequest {
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetHoldResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "release_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub release_reason: Option<String>,
    #[serde(rename = "released_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_at: Option<Timestamp>,
    #[serde(rename = "released_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes: Vec<HoldScope>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: GetHoldResponseStatus,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetHoldResponseStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetHoldError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListActivityRequest {
    #[serde(rename = "after")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListActivityResponse {
    #[serde(rename = "events")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub events: Vec<HoldActivity>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HoldActivity {
    #[serde(rename = "activity_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub activity_id: String,
    #[serde(rename = "actor_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_subject: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: std::collections::BTreeMap<String, serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListActivityError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListHoldsRequest {
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "status")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ListHoldsRequestStatus>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListHoldsRequestStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListHoldsResponse {
    #[serde(rename = "holds")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub holds: Vec<ListHoldsResponseHoldsItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListHoldsResponseHoldsItem {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "release_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub release_reason: Option<String>,
    #[serde(rename = "released_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_at: Option<Timestamp>,
    #[serde(rename = "released_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes: Vec<HoldScope>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ListHoldsResponseHoldsItemStatus,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListHoldsResponseHoldsItemStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListHoldsError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReleaseHoldRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReleaseHoldResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "release_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub release_reason: Option<String>,
    #[serde(rename = "released_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_at: Option<Timestamp>,
    #[serde(rename = "released_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes: Vec<HoldScope>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ReleaseHoldResponseStatus,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReleaseHoldResponseStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReleaseHoldError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RemoveScopeRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub subject: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RemoveScopeResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "hold_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hold_id: String,
    #[serde(rename = "legal_authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_authority: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "release_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub release_reason: Option<String>,
    #[serde(rename = "released_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_at: Option<Timestamp>,
    #[serde(rename = "released_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "scopes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scopes: Vec<HoldScope>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RemoveScopeResponseStatus,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RemoveScopeResponseStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "released")]
    Released,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RemoveScopeError {
    Forbidden,
    HoldReleased,
    IdempotencyConflict,
    InvalidRequest,
    NotFound,
    RevisionConflict,
    ScopeConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct LegalHoldAddScope;
impl RequestCapability for LegalHoldAddScope {
    type Request = AddScopeRequest;
    type Response = AddScopeResponse;
    type DomainError = AddScopeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ADD_SCOPE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).add_scope(context, request)
    }
}

#[derive(Debug)]
pub struct LegalHoldCreateHold;
impl RequestCapability for LegalHoldCreateHold {
    type Request = CreateHoldRequest;
    type Response = CreateHoldResponse;
    type DomainError = CreateHoldError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_HOLD_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_hold(context, request)
    }
}

#[derive(Debug)]
pub struct LegalHoldGetHold;
impl RequestCapability for LegalHoldGetHold {
    type Request = GetHoldRequest;
    type Response = GetHoldResponse;
    type DomainError = GetHoldError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_HOLD_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_hold(context, request)
    }
}

#[derive(Debug)]
pub struct LegalHoldListActivity;
impl RequestCapability for LegalHoldListActivity {
    type Request = ListActivityRequest;
    type Response = ListActivityResponse;
    type DomainError = ListActivityError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_ACTIVITY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_activity(context, request)
    }
}

#[derive(Debug)]
pub struct LegalHoldListHolds;
impl RequestCapability for LegalHoldListHolds {
    type Request = ListHoldsRequest;
    type Response = ListHoldsResponse;
    type DomainError = ListHoldsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_HOLDS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_holds(context, request)
    }
}

#[derive(Debug)]
pub struct LegalHoldReleaseHold;
impl RequestCapability for LegalHoldReleaseHold {
    type Request = ReleaseHoldRequest;
    type Response = ReleaseHoldResponse;
    type DomainError = ReleaseHoldError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RELEASE_HOLD_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).release_hold(context, request)
    }
}

#[derive(Debug)]
pub struct LegalHoldRemoveScope;
impl RequestCapability for LegalHoldRemoveScope {
    type Request = RemoveScopeRequest;
    type Response = RemoveScopeResponse;
    type DomainError = RemoveScopeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REMOVE_SCOPE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LegalHoldRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).remove_scope(context, request)
    }
}

impl serde::Serialize for AddScopeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AddScopeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CreateHoldError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateHoldError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetHoldError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetHoldError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListActivityError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListActivityError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListHoldsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListHoldsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReleaseHoldError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReleaseHoldError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RemoveScopeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::HoldReleased => serializer.serialize_str("hold_released"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeConflict => serializer.serialize_str("scope_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RemoveScopeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "hold_released" => Ok(Self::HoldReleased),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_conflict" => Ok(Self::ScopeConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_add_scope_request(value: &AddScopeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_add_scope_request(wire: &str) -> Result<AddScopeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_add_scope_response(value: &AddScopeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_add_scope_response(wire: &str) -> Result<AddScopeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_add_scope_error(value: &AddScopeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_add_scope_error(wire: &str) -> Result<AddScopeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_create_hold_request(value: &CreateHoldRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_hold_request(wire: &str) -> Result<CreateHoldRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_hold_response(value: &CreateHoldResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_hold_response(wire: &str) -> Result<CreateHoldResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_hold_error(value: &CreateHoldError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_hold_error(wire: &str) -> Result<CreateHoldError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_hold_request(value: &GetHoldRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_hold_request(wire: &str) -> Result<GetHoldRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_hold_response(value: &GetHoldResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_hold_response(wire: &str) -> Result<GetHoldResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_hold_error(value: &GetHoldError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_hold_error(wire: &str) -> Result<GetHoldError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_activity_request(value: &ListActivityRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_activity_request(wire: &str) -> Result<ListActivityRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_activity_response(value: &ListActivityResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_activity_response(wire: &str) -> Result<ListActivityResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_activity_error(value: &ListActivityError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_activity_error(wire: &str) -> Result<ListActivityError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_holds_request(value: &ListHoldsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_holds_request(wire: &str) -> Result<ListHoldsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_holds_response(value: &ListHoldsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_holds_response(wire: &str) -> Result<ListHoldsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_holds_error(value: &ListHoldsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_holds_error(wire: &str) -> Result<ListHoldsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_release_hold_request(value: &ReleaseHoldRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_release_hold_request(wire: &str) -> Result<ReleaseHoldRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_release_hold_response(value: &ReleaseHoldResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_release_hold_response(wire: &str) -> Result<ReleaseHoldResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_release_hold_error(value: &ReleaseHoldError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_release_hold_error(wire: &str) -> Result<ReleaseHoldError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_remove_scope_request(value: &RemoveScopeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_remove_scope_request(wire: &str) -> Result<RemoveScopeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_remove_scope_response(value: &RemoveScopeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_remove_scope_response(wire: &str) -> Result<RemoveScopeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_remove_scope_error(value: &RemoveScopeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_remove_scope_error(wire: &str) -> Result<RemoveScopeError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoLegalHoldAddScopeResult {
    fn __lenso_into_result(self) -> Result<Result<AddScopeResponse, AddScopeError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldAddScopeResult for Result<AddScopeResponse, AddScopeError> {
    fn __lenso_into_result(self) -> Result<Result<AddScopeResponse, AddScopeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldAddScopeResult for Result<Result<AddScopeResponse, AddScopeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AddScopeResponse, AddScopeError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldAddScopeResult for Result<AddScopeResponse, lenso_plugin_authoring::PluginError<AddScopeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AddScopeResponse, AddScopeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldAddScopeResult for Result<AddScopeResponse, LegalHoldAddScopeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AddScopeResponse, AddScopeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldAddScopeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldAddScopeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLegalHoldCreateHoldResult {
    fn __lenso_into_result(self) -> Result<Result<CreateHoldResponse, CreateHoldError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldCreateHoldResult for Result<CreateHoldResponse, CreateHoldError> {
    fn __lenso_into_result(self) -> Result<Result<CreateHoldResponse, CreateHoldError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldCreateHoldResult for Result<Result<CreateHoldResponse, CreateHoldError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateHoldResponse, CreateHoldError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldCreateHoldResult for Result<CreateHoldResponse, lenso_plugin_authoring::PluginError<CreateHoldError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateHoldResponse, CreateHoldError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldCreateHoldResult for Result<CreateHoldResponse, LegalHoldCreateHoldInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateHoldResponse, CreateHoldError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldCreateHoldInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldCreateHoldInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLegalHoldGetHoldResult {
    fn __lenso_into_result(self) -> Result<Result<GetHoldResponse, GetHoldError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldGetHoldResult for Result<GetHoldResponse, GetHoldError> {
    fn __lenso_into_result(self) -> Result<Result<GetHoldResponse, GetHoldError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldGetHoldResult for Result<Result<GetHoldResponse, GetHoldError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetHoldResponse, GetHoldError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldGetHoldResult for Result<GetHoldResponse, lenso_plugin_authoring::PluginError<GetHoldError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetHoldResponse, GetHoldError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldGetHoldResult for Result<GetHoldResponse, LegalHoldGetHoldInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetHoldResponse, GetHoldError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldGetHoldInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldGetHoldInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLegalHoldListActivityResult {
    fn __lenso_into_result(self) -> Result<Result<ListActivityResponse, ListActivityError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldListActivityResult for Result<ListActivityResponse, ListActivityError> {
    fn __lenso_into_result(self) -> Result<Result<ListActivityResponse, ListActivityError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldListActivityResult for Result<Result<ListActivityResponse, ListActivityError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListActivityResponse, ListActivityError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldListActivityResult for Result<ListActivityResponse, lenso_plugin_authoring::PluginError<ListActivityError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListActivityResponse, ListActivityError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldListActivityResult for Result<ListActivityResponse, LegalHoldListActivityInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListActivityResponse, ListActivityError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldListActivityInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldListActivityInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLegalHoldListHoldsResult {
    fn __lenso_into_result(self) -> Result<Result<ListHoldsResponse, ListHoldsError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldListHoldsResult for Result<ListHoldsResponse, ListHoldsError> {
    fn __lenso_into_result(self) -> Result<Result<ListHoldsResponse, ListHoldsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldListHoldsResult for Result<Result<ListHoldsResponse, ListHoldsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListHoldsResponse, ListHoldsError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldListHoldsResult for Result<ListHoldsResponse, lenso_plugin_authoring::PluginError<ListHoldsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListHoldsResponse, ListHoldsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldListHoldsResult for Result<ListHoldsResponse, LegalHoldListHoldsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListHoldsResponse, ListHoldsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldListHoldsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldListHoldsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLegalHoldReleaseHoldResult {
    fn __lenso_into_result(self) -> Result<Result<ReleaseHoldResponse, ReleaseHoldError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldReleaseHoldResult for Result<ReleaseHoldResponse, ReleaseHoldError> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseHoldResponse, ReleaseHoldError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldReleaseHoldResult for Result<Result<ReleaseHoldResponse, ReleaseHoldError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseHoldResponse, ReleaseHoldError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldReleaseHoldResult for Result<ReleaseHoldResponse, lenso_plugin_authoring::PluginError<ReleaseHoldError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseHoldResponse, ReleaseHoldError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldReleaseHoldResult for Result<ReleaseHoldResponse, LegalHoldReleaseHoldInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseHoldResponse, ReleaseHoldError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldReleaseHoldInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldReleaseHoldInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLegalHoldRemoveScopeResult {
    fn __lenso_into_result(self) -> Result<Result<RemoveScopeResponse, RemoveScopeError>, RuntimeFailure>;
}
impl __LensoIntoLegalHoldRemoveScopeResult for Result<RemoveScopeResponse, RemoveScopeError> {
    fn __lenso_into_result(self) -> Result<Result<RemoveScopeResponse, RemoveScopeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLegalHoldRemoveScopeResult for Result<Result<RemoveScopeResponse, RemoveScopeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RemoveScopeResponse, RemoveScopeError>, RuntimeFailure> { self }
}
impl __LensoIntoLegalHoldRemoveScopeResult for Result<RemoveScopeResponse, lenso_plugin_authoring::PluginError<RemoveScopeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RemoveScopeResponse, RemoveScopeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLegalHoldRemoveScopeResult for Result<RemoveScopeResponse, LegalHoldRemoveScopeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RemoveScopeResponse, RemoveScopeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LegalHoldRemoveScopeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LegalHoldRemoveScopeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait LegalHoldProvider: fmt::Debug + 'static {
    fn add_scope(&self, context: InvocationContext, request: AddScopeRequest) -> NativeRequestFuture<LegalHoldAddScope>;
    fn create_hold(&self, context: InvocationContext, request: CreateHoldRequest) -> NativeRequestFuture<LegalHoldCreateHold>;
    fn get_hold(&self, context: InvocationContext, request: GetHoldRequest) -> NativeRequestFuture<LegalHoldGetHold>;
    fn list_activity(&self, context: InvocationContext, request: ListActivityRequest) -> NativeRequestFuture<LegalHoldListActivity>;
    fn list_holds(&self, context: InvocationContext, request: ListHoldsRequest) -> NativeRequestFuture<LegalHoldListHolds>;
    fn release_hold(&self, context: InvocationContext, request: ReleaseHoldRequest) -> NativeRequestFuture<LegalHoldReleaseHold>;
    fn remove_scope(&self, context: InvocationContext, request: RemoveScopeRequest) -> NativeRequestFuture<LegalHoldRemoveScope>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_legal_hold {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLegalHold;
        impl $crate::LegalHoldProvider for $plugin {
        fn add_scope(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::AddScopeRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldAddScope> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::add_scope(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldAddScopeResult::__lenso_into_result(result)
            })
        }
        fn create_hold(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::CreateHoldRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldCreateHold> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_hold(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldCreateHoldResult::__lenso_into_result(result)
            })
        }
        fn get_hold(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::GetHoldRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldGetHold> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_hold(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldGetHoldResult::__lenso_into_result(result)
            })
        }
        fn list_activity(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::ListActivityRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldListActivity> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_activity(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldListActivityResult::__lenso_into_result(result)
            })
        }
        fn list_holds(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::ListHoldsRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldListHolds> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_holds(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldListHoldsResult::__lenso_into_result(result)
            })
        }
        fn release_hold(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::ReleaseHoldRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldReleaseHold> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::release_hold(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldReleaseHoldResult::__lenso_into_result(result)
            })
        }
        fn remove_scope(&self, context: __LensoNativeSupportLegalHold::InvocationContext, request: $crate::RemoveScopeRequest) -> __LensoNativeSupportLegalHold::NativeRequestFuture<$crate::LegalHoldRemoveScope> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::remove_scope(&plugin, context, request).await;
                $crate::__LensoIntoLegalHoldRemoveScopeResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct LegalHoldRequestEndpoint { provider: Rc<dyn LegalHoldProvider> }

#[derive(Debug)]
pub struct LegalHoldEndpoint<P: LegalHoldProvider> { provider: Rc<P>, request_endpoint: LegalHoldRequestEndpoint }
impl<P: LegalHoldProvider> LegalHoldEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn LegalHoldProvider> = provider.clone();
        Self { provider, request_endpoint: LegalHoldRequestEndpoint { provider: request_provider } }
    }
}

impl<P: LegalHoldProvider> NativeRequestEndpoint for LegalHoldEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ADD_SCOPE_OPERATION,
        CREATE_HOLD_OPERATION,
        GET_HOLD_OPERATION,
        LIST_ACTIVITY_OPERATION,
        LIST_HOLDS_OPERATION,
        RELEASE_HOLD_OPERATION,
        REMOVE_SCOPE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ADD_SCOPE_OPERATION => {
                let Ok(request) = request.downcast::<AddScopeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).add_scope(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CREATE_HOLD_OPERATION => {
                let Ok(request) = request.downcast::<CreateHoldRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_hold(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_HOLD_OPERATION => {
                let Ok(request) = request.downcast::<GetHoldRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_hold(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_ACTIVITY_OPERATION => {
                let Ok(request) = request.downcast::<ListActivityRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_activity(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_HOLDS_OPERATION => {
                let Ok(request) = request.downcast::<ListHoldsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_holds(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RELEASE_HOLD_OPERATION => {
                let Ok(request) = request.downcast::<ReleaseHoldRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).release_hold(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REMOVE_SCOPE_OPERATION => {
                let Ok(request) = request.downcast::<RemoveScopeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).remove_scope(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_legal_hold {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::LegalHoldEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_legal_hold {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_legal_hold!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct LegalHoldClient {
    add_scope: NativeRequestHandle<LegalHoldAddScope>,
    create_hold: NativeRequestHandle<LegalHoldCreateHold>,
    get_hold: NativeRequestHandle<LegalHoldGetHold>,
    list_activity: NativeRequestHandle<LegalHoldListActivity>,
    list_holds: NativeRequestHandle<LegalHoldListHolds>,
    release_hold: NativeRequestHandle<LegalHoldReleaseHold>,
    remove_scope: NativeRequestHandle<LegalHoldRemoveScope>,
}
impl LegalHoldClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn add_scope(&self, request: AddScopeRequest) -> Result<AddScopeResponse, LegalHoldAddScopeInvocationError> {
        self.add_scope.invoke(ADD_SCOPE_OPERATION, request).await
            .map_err(LegalHoldAddScopeInvocationError::Runtime)?
            .map_err(LegalHoldAddScopeInvocationError::Domain)
    }

    pub async fn add_scope_with_context(&self, context: InvocationContext, request: AddScopeRequest) -> Result<AddScopeResponse, LegalHoldAddScopeInvocationError> {
        self.add_scope.invoke_with_context(ADD_SCOPE_OPERATION, context, request).await
            .map_err(LegalHoldAddScopeInvocationError::Runtime)?
            .map_err(LegalHoldAddScopeInvocationError::Domain)
    }

    pub async fn create_hold(&self, request: CreateHoldRequest) -> Result<CreateHoldResponse, LegalHoldCreateHoldInvocationError> {
        self.create_hold.invoke(CREATE_HOLD_OPERATION, request).await
            .map_err(LegalHoldCreateHoldInvocationError::Runtime)?
            .map_err(LegalHoldCreateHoldInvocationError::Domain)
    }

    pub async fn create_hold_with_context(&self, context: InvocationContext, request: CreateHoldRequest) -> Result<CreateHoldResponse, LegalHoldCreateHoldInvocationError> {
        self.create_hold.invoke_with_context(CREATE_HOLD_OPERATION, context, request).await
            .map_err(LegalHoldCreateHoldInvocationError::Runtime)?
            .map_err(LegalHoldCreateHoldInvocationError::Domain)
    }

    pub async fn get_hold(&self, request: GetHoldRequest) -> Result<GetHoldResponse, LegalHoldGetHoldInvocationError> {
        self.get_hold.invoke(GET_HOLD_OPERATION, request).await
            .map_err(LegalHoldGetHoldInvocationError::Runtime)?
            .map_err(LegalHoldGetHoldInvocationError::Domain)
    }

    pub async fn get_hold_with_context(&self, context: InvocationContext, request: GetHoldRequest) -> Result<GetHoldResponse, LegalHoldGetHoldInvocationError> {
        self.get_hold.invoke_with_context(GET_HOLD_OPERATION, context, request).await
            .map_err(LegalHoldGetHoldInvocationError::Runtime)?
            .map_err(LegalHoldGetHoldInvocationError::Domain)
    }

    pub async fn list_activity(&self, request: ListActivityRequest) -> Result<ListActivityResponse, LegalHoldListActivityInvocationError> {
        self.list_activity.invoke(LIST_ACTIVITY_OPERATION, request).await
            .map_err(LegalHoldListActivityInvocationError::Runtime)?
            .map_err(LegalHoldListActivityInvocationError::Domain)
    }

    pub async fn list_activity_with_context(&self, context: InvocationContext, request: ListActivityRequest) -> Result<ListActivityResponse, LegalHoldListActivityInvocationError> {
        self.list_activity.invoke_with_context(LIST_ACTIVITY_OPERATION, context, request).await
            .map_err(LegalHoldListActivityInvocationError::Runtime)?
            .map_err(LegalHoldListActivityInvocationError::Domain)
    }

    pub async fn list_holds(&self, request: ListHoldsRequest) -> Result<ListHoldsResponse, LegalHoldListHoldsInvocationError> {
        self.list_holds.invoke(LIST_HOLDS_OPERATION, request).await
            .map_err(LegalHoldListHoldsInvocationError::Runtime)?
            .map_err(LegalHoldListHoldsInvocationError::Domain)
    }

    pub async fn list_holds_with_context(&self, context: InvocationContext, request: ListHoldsRequest) -> Result<ListHoldsResponse, LegalHoldListHoldsInvocationError> {
        self.list_holds.invoke_with_context(LIST_HOLDS_OPERATION, context, request).await
            .map_err(LegalHoldListHoldsInvocationError::Runtime)?
            .map_err(LegalHoldListHoldsInvocationError::Domain)
    }

    pub async fn release_hold(&self, request: ReleaseHoldRequest) -> Result<ReleaseHoldResponse, LegalHoldReleaseHoldInvocationError> {
        self.release_hold.invoke(RELEASE_HOLD_OPERATION, request).await
            .map_err(LegalHoldReleaseHoldInvocationError::Runtime)?
            .map_err(LegalHoldReleaseHoldInvocationError::Domain)
    }

    pub async fn release_hold_with_context(&self, context: InvocationContext, request: ReleaseHoldRequest) -> Result<ReleaseHoldResponse, LegalHoldReleaseHoldInvocationError> {
        self.release_hold.invoke_with_context(RELEASE_HOLD_OPERATION, context, request).await
            .map_err(LegalHoldReleaseHoldInvocationError::Runtime)?
            .map_err(LegalHoldReleaseHoldInvocationError::Domain)
    }

    pub async fn remove_scope(&self, request: RemoveScopeRequest) -> Result<RemoveScopeResponse, LegalHoldRemoveScopeInvocationError> {
        self.remove_scope.invoke(REMOVE_SCOPE_OPERATION, request).await
            .map_err(LegalHoldRemoveScopeInvocationError::Runtime)?
            .map_err(LegalHoldRemoveScopeInvocationError::Domain)
    }

    pub async fn remove_scope_with_context(&self, context: InvocationContext, request: RemoveScopeRequest) -> Result<RemoveScopeResponse, LegalHoldRemoveScopeInvocationError> {
        self.remove_scope.invoke_with_context(REMOVE_SCOPE_OPERATION, context, request).await
            .map_err(LegalHoldRemoveScopeInvocationError::Runtime)?
            .map_err(LegalHoldRemoveScopeInvocationError::Domain)
    }
}

impl CapabilityClient for LegalHoldClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            add_scope: dependencies.one::<LegalHoldAddScope>()?,
            create_hold: dependencies.one::<LegalHoldCreateHold>()?,
            get_hold: dependencies.one::<LegalHoldGetHold>()?,
            list_activity: dependencies.one::<LegalHoldListActivity>()?,
            list_holds: dependencies.one::<LegalHoldListHolds>()?,
            release_hold: dependencies.one::<LegalHoldReleaseHold>()?,
            remove_scope: dependencies.one::<LegalHoldRemoveScope>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for LegalHoldClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    add_scope: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldAddScope>()?,
                    create_hold: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldCreateHold>()?,
                    get_hold: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldGetHold>()?,
                    list_activity: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldListActivity>()?,
                    list_holds: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldListHolds>()?,
                    release_hold: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldReleaseHold>()?,
                    remove_scope: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LegalHoldRemoveScope>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldAddScopeInvocationError {
    Domain(AddScopeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldCreateHoldInvocationError {
    Domain(CreateHoldError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldGetHoldInvocationError {
    Domain(GetHoldError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldListActivityInvocationError {
    Domain(ListActivityError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldListHoldsInvocationError {
    Domain(ListHoldsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldReleaseHoldInvocationError {
    Domain(ReleaseHoldError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LegalHoldRemoveScopeInvocationError {
    Domain(RemoveScopeError),
    Runtime(RuntimeFailure),
}
